// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Cp3dS4tTU_q0QRvTL9cWXt9bbASqeG4',
    appId: '1:1049840318668:web:7f5ce232d18f06eaf3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    authDomain: 'property-c1175.firebaseapp.com',
    storageBucket: 'property-c1175.appspot.com',
    measurementId: 'G-BKP6TFC6T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7kUBhws6UYWaZDsP1BLVrxR_Jo-xBD8',
    appId: '1:1049840318668:android:bf5bd87b17c435b7f3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    storageBucket: 'property-c1175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxqMV9bRvp4URNFvns4HxHLPSVLYrgbw',
    appId: '1:1049840318668:ios:113ea3a54b4b4967f3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    storageBucket: 'property-c1175.appspot.com',
    iosBundleId: 'com.example.property',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxqMV9bRvp4URNFvns4HxHLPSVLYrgbw',
    appId: '1:1049840318668:ios:ed162f58efe9830ef3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    storageBucket: 'property-c1175.appspot.com',
    iosBundleId: 'com.example.property.RunnerTests',
  );
}
